version: '3'

services:
  app:
    container_name: books-backend
    restart: on-failure
    volumes:
      - ./backend:/app
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database


  database:
    image: postgres:14
    container_name: books-database
    restart: always
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"


  frontend:
    build:
      context: ./frontend
    restart: always
    container_name: books-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app